spring.application.name=product-service
server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/bd_product
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.locations=classpath:/db_migration